apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mapr-spark-pvc
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 50Gi
  storageClassName: nfs
  volumeName: mapr-spark-pv
