{{- if .Values.maprSparkServiceSecret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.maprSparkServiceSecret.name }} # Must always be server
data:
  {{ .Values.maprSparkServiceSecret.ticket_name }}: {{ .Values.maprSparkServiceSecret.ticket_value }}
{{- end }}

