{{- if .Values.maprSparkUserSecret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name:   {{ .Values.maprSparkUserSecret.name }}
data:
    {{ .Values.maprSparkUserSecret.ticket_name }}: {{ .Values.maprSparkUserSecret.ticket_value }}
{{- end }}
