{{- if .Values.maprClusterConfigmap.create -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.maprClusterConfigmap.name }} # Must be cluster-cm
data:
  {{ .Values.maprClusterConfigmap.name }}: |+
    {{ .Values.maprClusterConfigmap.name }}
{{- end }}